In [75]:
import numpy as np
import pandas as pd

In [76]:
link = 'sample.xlsx'
sample = pd.read_excel(link)
sample.head()

  STUDENTS
0   STEM#1
1   STEM#2
2   STEM#3
3   STEM#4
4   STEM#5

In [77]:
listOfstem = sample.to_numpy().tolist()
listOfstem

[['STEM#1'],
 ['STEM#2'],
 ['STEM#3'],
 ['STEM#4'],
 ['STEM#5'],
 ['STEM#6'],
 ['STEM#7'],
 ['STEM#8'],
 ['STEM#9'],
 ['STEM#10'],
 ['STEM#11'],
 ['STEM#12'],
 ['STEM#13'],
 ['STEM#14'],
 ['STEM#15'],
 ['STEM#16'],
 ['STEM#17'],
 ['STEM#18'],
 ['STEM#19'],
 ['STEM#20'],
 ['STEM#21'],
 ['STEM#22'],
 ['STEM#23'],
 ['STEM#24'],
 ['STEM#25'],
 ['STEM#26'],
 ['STEM#27'],
 ['STEM#28'],
 ['STEM#29'],
 ['STEM#30'],
 ['STEM#31'],
 ['STEM#32'],
 ['STEM#33'],
 ['STEM#34'],
 ['STEM#35'],
 ['STEM#36'],
 ['STEM#37'],
 ['STEM#38'],
 ['STEM#39'],
 ['STEM#40'],
 ['STEM#41'],
 ['STEM#42'],
 ['STEM#43'],
 ['STEM#44'],
 ['STEM#45'],
 ['STEM#46'],
 ['STEM#47'],
 ['STEM#48'],
 ['STEM#49'],
 ['STEM#50'],
 ['STEM#51'],
 ['STEM#52'],
 ['STEM#53'],
 ['STEM#54'],
 ['STEM#55'],
 ['STEM#56'],
 ['STEM#57'],
 ['STEM#58'],
 ['STEM#59'],
 ['STEM#60'],
 ['STEM#61'],
 ['STEM#62'],
 ['STEM#63'],
 ['STEM#64'],
 ['STEM#65'],
 ['STEM#66'],
 ['STEM#67'],
 ['STEM#68'],
 ['STEM#69'],
 ['STEM#70'],
 ['STEM#71'],
 ['STEM#72']]

In [78]:
import random
rans = random.sample(range(0, len(listOfstem)), len(listOfstem))
#len(set(rans))

In [79]:
listOfrandom = [ listOfstem[a] for a in rans]
listOfrandom

[['STEM#48'],
 ['STEM#34'],
 ['STEM#38'],
 ['STEM#62'],
 ['STEM#70'],
 ['STEM#39'],
 ['STEM#52'],
 ['STEM#44'],
 ['STEM#67'],
 ['STEM#42'],
 ['STEM#43'],
 ['STEM#3'],
 ['STEM#16'],
 ['STEM#45'],
 ['STEM#65'],
 ['STEM#1'],
 ['STEM#37'],
 ['STEM#26'],
 ['STEM#9'],
 ['STEM#66'],
 ['STEM#58'],
 ['STEM#6'],
 ['STEM#12'],
 ['STEM#28'],
 ['STEM#23'],
 ['STEM#25'],
 ['STEM#64'],
 ['STEM#18'],
 ['STEM#35'],
 ['STEM#61'],
 ['STEM#7'],
 ['STEM#53'],
 ['STEM#31'],
 ['STEM#50'],
 ['STEM#5'],
 ['STEM#57'],
 ['STEM#10'],
 ['STEM#2'],
 ['STEM#63'],
 ['STEM#30'],
 ['STEM#59'],
 ['STEM#69'],
 ['STEM#40'],
 ['STEM#29'],
 ['STEM#32'],
 ['STEM#21'],
 ['STEM#51'],
 ['STEM#17'],
 ['STEM#8'],
 ['STEM#4'],
 ['STEM#60'],
 ['STEM#56'],
 ['STEM#20'],
 ['STEM#71'],
 ['STEM#13'],
 ['STEM#49'],
 ['STEM#41'],
 ['STEM#46'],
 ['STEM#27'],
 ['STEM#22'],
 ['STEM#54'],
 ['STEM#72'],
 ['STEM#11'],
 ['STEM#47'],
 ['STEM#15'],
 ['STEM#68'],
 ['STEM#24'],
 ['STEM#33'],
 ['STEM#36'],
 ['STEM#19'],
 ['STEM#14'],
 ['STEM#55']]

In [80]:
#Number of team members
N_TEAM = 4
a = 0
x = len(listOfrandom)
finalResult = []
while  x != 0:
   # print(listOfrandom[a: a+N_TEAM]) 
    if x%N_TEAM != 0 :
        print("Number of persons must be divideable on the number of team members")
        break
    finalResult.append(listOfrandom[a: a+N_TEAM]) 
    a += N_TEAM
    x -= N_TEAM
print(finalResult)

[[['STEM#48'], ['STEM#34'], ['STEM#38'], ['STEM#62']], [['STEM#70'], ['STEM#39'], ['STEM#52'], ['STEM#44']], [['STEM#67'], ['STEM#42'], ['STEM#43'], ['STEM#3']], [['STEM#16'], ['STEM#45'], ['STEM#65'], ['STEM#1']], [['STEM#37'], ['STEM#26'], ['STEM#9'], ['STEM#66']], [['STEM#58'], ['STEM#6'], ['STEM#12'], ['STEM#28']], [['STEM#23'], ['STEM#25'], ['STEM#64'], ['STEM#18']], [['STEM#35'], ['STEM#61'], ['STEM#7'], ['STEM#53']], [['STEM#31'], ['STEM#50'], ['STEM#5'], ['STEM#57']], [['STEM#10'], ['STEM#2'], ['STEM#63'], ['STEM#30']], [['STEM#59'], ['STEM#69'], ['STEM#40'], ['STEM#29']], [['STEM#32'], ['STEM#21'], ['STEM#51'], ['STEM#17']], [['STEM#8'], ['STEM#4'], ['STEM#60'], ['STEM#56']], [['STEM#20'], ['STEM#71'], ['STEM#13'], ['STEM#49']], [['STEM#41'], ['STEM#46'], ['STEM#27'], ['STEM#22']], [['STEM#54'], ['STEM#72'], ['STEM#11'], ['STEM#47']], [['STEM#15'], ['STEM#68'], ['STEM#24'], ['STEM#33']], [['STEM#36'], ['STEM#19'], ['STEM#14'], ['STEM#55']]]

In [81]:
FINAL  = pd.DataFrame(finalResult)
FINAL
#use the line below to make an excel file by the result
#FINAL.to_excel('FINAL.xlsx')

            0          1          2          3
0   [STEM#48]  [STEM#34]  [STEM#38]  [STEM#62]
1   [STEM#70]  [STEM#39]  [STEM#52]  [STEM#44]
2   [STEM#67]  [STEM#42]  [STEM#43]   [STEM#3]
3   [STEM#16]  [STEM#45]  [STEM#65]   [STEM#1]
4   [STEM#37]  [STEM#26]   [STEM#9]  [STEM#66]
5   [STEM#58]   [STEM#6]  [STEM#12]  [STEM#28]
6   [STEM#23]  [STEM#25]  [STEM#64]  [STEM#18]
7   [STEM#35]  [STEM#61]   [STEM#7]  [STEM#53]
8   [STEM#31]  [STEM#50]   [STEM#5]  [STEM#57]
9   [STEM#10]   [STEM#2]  [STEM#63]  [STEM#30]
10  [STEM#59]  [STEM#69]  [STEM#40]  [STEM#29]
11  [STEM#32]  [STEM#21]  [STEM#51]  [STEM#17]
12   [STEM#8]   [STEM#4]  [STEM#60]  [STEM#56]
13  [STEM#20]  [STEM#71]  [STEM#13]  [STEM#49]
14  [STEM#41]  [STEM#46]  [STEM#27]  [STEM#22]
15  [STEM#54]  [STEM#72]  [STEM#11]  [STEM#47]
16  [STEM#15]  [STEM#68]  [STEM#24]  [STEM#33]
17  [STEM#36]  [STEM#19]  [STEM#14]  [STEM#55]